checking if condition between jobs

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -61,6 +61,8 @@ jobs:
 
   check-consumer-modified:
     runs-on: ubuntu-latest
+    outputs:
+      consumer_files_modified: ${{ steps.check_modifications.outputs.consumer_files_modified }}
     steps:
       - uses: actions/checkout@v2
         with:
@@ -73,21 +75,21 @@ jobs:
         run: |
           if git diff --name-only origin/${{ github.base_ref }}...origin/${{ github.head_ref }} | grep -q '.*\.consumer\.pact\.spec\.ts'; then
             echo "::set-output name=consumer_files_modified::true"
-            echo "consumer modified"
+            echo "consumer files were modified. Aborting"
           else
             echo "::set-output name=consumer_files_modified::false"
             echo "consumer not modified"
           fi
           echo consumer_files_modified ::consumer_files_modified
-      - name: Abort if any *.consumer.pact.spec.ts was modified
-        if: steps.check_modifications.outputs.consumer_files_modified == 'true'
-        run: |
-          echo "*.consumer.yaml was modified, aborting workflow."
-          exit 1
+      # - name: Abort if any *.consumer.pact.spec.ts was modified
+      #   if: steps.check_modifications.outputs.consumer_files_modified == 'true'
+      #   run: |
+      #     echo "*.consumer.yaml was modified, aborting workflow."
+      #     exit 1
           
     
   test:
-    # if: needs.check-consumer-running.outputs.is_consumer_runing == 'false'
+    if: needs.check-consumer-modified.outputs.consumer_files_modified == 'false'
     runs-on: ubuntu-latest
     needs: check-consumer-modified
     steps:
